# Generated by Django 3.2.9 on 2022-05-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_davomat_group_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
